IDIR = include
ODIR = obj
SRCDIR = src
CC = gcc

#usage: make frsim => will build all simulations

frsim:
	$(info **********************************)
	$(info * ==> FRsim (n-Dimensional, perturbated random-walks))
	$(info **********************************)
	make -f makefile.complete

clean:
	rm $(ODIR)/*
	rm frsim
